### ISSUE TITLE
Platform configuration

### ISSUE THREAD

**Issue by A-Hilaly** [medtune/platform#8]
Make the app more flexible with startup and in-production configuration.

An example of yaml configuration

Note that some configuration cannot be changed while running like Port/Addr etc. But some might be remove/edited without impacting server performance

```yaml
meta:
  name: amine.in
  description: personal web site
  version: 2.0.0

server:
  mode: LAS 
  port: 8005
  addr: localhost

database:
  type: postgres
  prod: amine.in
  debug: amine.in-debug
  test: amine.in-test
  creds:
    host: localhost
    port: 5432
    user: amine
    password: a
  
api:
  active: false
  tokens: ["1"]

session:
  type: cookie
  name: default-session
  secret: A0123456789

memcache: 
  capacity: 1000
  lifetime: 86400
  interval: x
  delay: x

assets:
  repos: a-hilaly/assets
  direction: .

sync:
  posts:
    db: true
    static: false

accounts:
  - login: amine
    password: password

crypto:
  algo: id
  salt: --xyz=??=xyz--

logging:
  type:
  config: 

public:
  static: ./static

links:
  github: a-hilaly
  twitter: aminedotin
  gplus:

sched:
  jobs: 
    - name: backup
      delta: 86400
    - name: sync-tags
      delta: 86400
    - name: 

```
